[package]
name = "volume-noise-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.32.0"
noise = "0.9.0"
image = "0.25.9"
half = "2.7.1"
rayon = "1.11.0"
bon = "3.8.2"
rand = "0.10.0"
atomic_float = "1.1.0"
trait-set = "0.3.0"